version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "hemantpatilanveshak"
github_repo = "cicd-demo-custom"
deployment_branch = "dev-hemant-demo"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev-demo.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::352241563310:role/aws-sam-cli-managed-dev-demo-PipelineExecutionRole-1MSC5OMXCW4L3"
cloudformation_execution_role = "arn:aws:iam::352241563310:role/aws-sam-cli-managed-dev-d-CloudFormationExecutionR-1ESLW8L0AO8WY"
artifacts_bucket = "aws-sam-cli-managed-dev-demo-pipe-artifactsbucket-kx21r6m4z1z8"
image_repository = ""
region = "us-east-1"

[prod-demo.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::352241563310:role/aws-sam-cli-managed-prod-dem-PipelineExecutionRole-LBOU6HXSDWX4"
cloudformation_execution_role = "arn:aws:iam::352241563310:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-148QD4TMXB85C"
artifacts_bucket = "aws-sam-cli-managed-prod-demo-pip-artifactsbucket-1az2npndfmtmj"
image_repository = ""
region = "us-east-1"
